### ISSUE TITLE
Could not resolve module @angular/core

### ISSUE THREAD

**Issue by dmitrysteblyuk** [angular/closure-demo#24]
After git clone and npm install (I do not make any changes in the project) when I run ```yarn run build``` I've got this error:

```
yarn run v1.1.0
$ ngc -p src && yarn run closure && ./size_report.sh
Error: Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (C:\Workspace\closure-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:31256:30)
    at StaticReflector.findDeclaration (C:\Workspace\closure-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:29723:63)
    at StaticReflector.initializeConversionMap (C:\Workspace\closure-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:29988:36)
    at new StaticReflector (C:\Workspace\closure-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:29673:14)
    at Object.createAotCompiler (C:\Workspace\closure-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:31496:44)
    at AngularCompilerProgram._createProgramWithBasicStubs (C:\Workspace\closure-demo\node_modules\@angular\compiler-cli\src\transformers\program.js:304:37)
    at AngularCompilerProgram.initSync (C:\Workspace\closure-demo\node_modules\@angular\compiler-cli\src\transformers\program.js:278:23)
    at AngularCompilerProgram.get [as tsProgram] (C:\Workspace\closure-demo\node_modules\@angular\compiler-cli\src\transformers\program.js:237:22)
    at AngularCompilerProgram.getTsOptionDiagnostics (C:\Workspace\closure-demo\node_modules\@angular\compiler-cli\src\transformers\program.js:75:20)
    at defaultGatherDiagnostics (C:\Workspace\closure-demo\node_modules\@angular\compiler-cli\src\perform_compile.js:170:34)
```

Environment: Windows 10, npm 3.10.10, node 6.11.4

**Comment by papakai** [comment]
```bash
ERROR in Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:31884:30)
    at StaticReflector.findDeclaration (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:30371:63)
    at StaticReflector.initializeConversionMap (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:30636:36)
    at new StaticReflector (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:30317:14)
    at Object.createAotCompiler (/home/kai/git/fmonitorcli/node_modules/@angular/compiler/bundles/compiler.umd.js:32124:44)
    at AngularCompilerProgram._createCompiler (/home/kai/git/fmonitorcli/node_modules/@angular/compiler-cli/src/transformers/program.js:405:37)
    at AngularCompilerProgram.get [as compiler] (/home/kai/git/fmonitorcli/node_modules/@angular/compiler-cli/src/transformers/program.js:314:22)
    at AngularCompilerProgram.listLazyRoutes (/home/kai/git/fmonitorcli/node_modules/@angular/compiler-cli/src/transformers/program.js:157:20)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/kai/git/fmonitorcli/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/home/kai/git/fmonitorcli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:247:66)
    at Promise.resolve.then.then (/home/kai/git/fmonitorcli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:538:50)
```

similar issue here.

What I did: I have two apps configured, both as separate subfolders under /src e.g. /src/full and /src/tv. These folders are configured as root folder for these apps.
npm install got correctly processed and node_modules includes @angular/core module.

Looks like this is a path issue somewhere? Maybe the above description helps to figure a solution out.
