### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ghost** [angular/closure-demo#28]
The application throws an error when I run 
**ngr build dev --serve --watch**

Here is the stack for it - 
`npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN codelyzer@4.0.1 requires a peer of tslint@^5.0.0 but none was installed.
npm verb 
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm verb exit [ 0, true ]
npm info ok 
Aditya:angular2-rollup adityashukla$ ngr build dev --serve --watch
[01:02:17] LOG angular-rollup 1.0.0-rc.1   
/usr/local/lib/node_modules/angular-rollup/cli.js:169
        if (program.build === 'dev' && program.jit === undefined && parseInt(projectPackage.dependencies['@angular/core'].split('.')[0]) < 5) {
                                                                                                                         ^

TypeError: Cannot read property 'split' of undefined
    at Timeout.init [as _onTimeout] (/usr/local/lib/node_modules/angular-rollup/cli.js:169:122)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
`

**Comment by steveblue** [comment]
@adishuk you are using `angular-rollup` which is great, but you should file the bug in that repo. This is not an issue with closure or the closure-demo, but that repository. File an issue or login to the gitter channel and I will help you get started with the repo. This is most likely a support request. https://github.com/steveblue/angular2-rollup/issues

**Comment by ghost** [comment]
Thanks. Will follow up over there if I am not able to resolve the issue on my own. Apologies.

**Comment by steveblue** [comment]
@adisuk Im on gitter all day today if you need support https://gitter.im/angular2-rollup/Lobby
